- _includes/article/deep_dive/related_articles.html
- _includes/article/pagination.liquid
- _includes/default/assigns.liquid
- _includes/default/header.liquid
- _includes/default/header_link_to_about.liquid
- _includes/journal/assigns.liquid
- _includes/journal/nav_categories.liquid
- _layouts/archive/category.html
- _layouts/article.html
- _layouts/author.html
- _layouts/default.html
- _layouts/journal.html
- jekyll-theme-platoniq-journal.gemspec
this are the expected urls:
```
archives:
permalink: /:locale/:journal-uid/:category/
articles:
permalink: /:locale/:journal-uid/:category/:uid/
journals:
permalink: /:locale/:uid/
pages:
permalink: /:locale/:uid/
```
- so a page will result: `/en/about/`
- a journal volume: `/en/wilder-journal-1/`
- a category archive: `/en/wilder-journal-1/interviews/`
- an article: `/en/wilder-journal-1/interviews/conversations-with-angela/`
> feat/ pretty urls

- _includes/journal/section_reports.liquid
- _includes/journal/section_stickers.liquid
- _includes/journal/section_stories.liquid
- _includes/journal/section_varis.liquid
- _layouts/archive/category.html
When the _pretty urls_ #4  where applied some links to the category archive didn't get updated, this PR fixes it.
> fix: links to archive

- _config.yml
- _includes/netlifycms/collections/Article.liquid
- _layouts/netlifycms/config.yml
This PR adds more fields to the `Article` collection to the cms editor
> Feat add to cms more Article fields

- _sass/partials/_page.scss
- jekyll-theme-platoniq-journal.gemspec
> Style article body lists

- _includes/netlifycms/collections/Site.yml
- jekyll-theme-platoniq-journal.gemspec
set cms on local backend for `development` environment
```
{% if jekyll.environment == "development" %}
local_backend: true
{% endif %}
```
> chore(cms): local_bakend on dev env

- _includes/netlifycms/collections/Article.liquid
- _includes/netlifycms/scripts/editor_component_documents_tag.liquid
- assets/js/cms.js
- jekyll-theme-platoniq-journal.gemspec
Related to https://github.com/Platoniq/jekyll-plugin-platoniq-journal/pull/11
> feat(cms_documents): create editor component for documents tag

- _includes/article/hero.liquid
- _includes/netlifycms/collections/Article.liquid
- jekyll-theme-platoniq-journal.gemspec
> feat(article): add interviewee to hero

- _layouts/archive/category.html
- _layouts/article.html
- _layouts/base.html
- _sass/partials/_page.scss
- _sass/partials/_sections.scss
- _sass/partials/_share.scss
- jekyll-theme-platoniq-journal.gemspec
To prevent styles inside #page taking preference over other, more specific ones
> fix(page_css_id): change #page to .page

- _includes/article/assigns.liquid
- _includes/article/hero.liquid
- _includes/article/related_articles.liquid
- _includes/article/share.liquid
- _includes/default/assigns.liquid
- _includes/default/related_article.liquid
- _includes/journal/assigns.liquid
- jekyll-theme-platoniq-journal.gemspec
- Fix journal volume link and make t_authored_by available globally
- Related articles
- Fix related articles list
> feat(related_articles)

- _data/i18n/en/global.yml
- _data/i18n/es/global.yml
- _includes/article/assigns.liquid
- _includes/article/hero.liquid
- _includes/default/related_article.liquid
- _includes/netlifycms/collections/StickerPack.liquid
- _layouts/archive/category.html
- _layouts/article.html
- _layouts/base.html
- _layouts/default.html
- _layouts/page.html
- _layouts/sticker_pack.html
- _sass/partials/_page.scss
- _sass/partials/_sections.scss
- _sass/partials/_share.scss
- _sass/partials/page/_elements.scss
- _sass/partials/page/_header.scss
- _sass/plugins/tags/_gallery.scss
- _sass/plugins/tags/_links.scss
- _sass/plugins/tags/_quote.scss
- assets/media/icons/icon-dot.svg
- jekyll-theme-platoniq-journal.gemspec
- Rename classes, fix some  article styles
- Use author name + author for stickers
- Fix list style in categories
- Fix related articles
> (fix): styles, related articles

- _data/i18n/en/global.yml
- _data/i18n/es/global.yml
- _includes/default/assigns.liquid
- _includes/default/header.liquid
- _includes/default/header_link_to_about.liquid
- _includes/default/header_logo.liquid
- _includes/default/header_sitemap_selector.liquid
- _includes/default/header_volume_selector.liquid
- _includes/netlifycms/collections/Site.yml
- _sass/partials/_header.scss
- assets/js/main.js
- jekyll-theme-platoniq-journal.gemspec
> feat(sitemap_menu)

- _includes/article/related_articles.liquid
- _sass/partials/_related_articles.scss
- _sass/partials/_sections.scss
- assets/js/main.js
- jekyll-theme-platoniq-journal.gemspec
- Fix style for related articles
- Add url param to CTA
> (feat): Improve CTA and related articles

- _includes/default/head.liquid
- _includes/netlifycms/collections/Article.liquid
- _includes/netlifycms/scripts/editor_component_file_tag.liquid
- _includes/plugins/file.liquid
- _includes/plugins/gallery.liquid
- _sass/partials/home/_home_reports.scss
- _sass/plugins/tags/_file.scss
- _sass/plugins/tags/_gallery.scss
- assets/js/main.js
- jekyll-theme-platoniq-journal.gemspec
- Bring image to front if sticker for report thumbnails
- Defer loading of netlifycms script
- Bump version
- Add update date to articles
- Improve gallery with multiple images
- Add alt color to file block
> Improve details (galleries, file block, images)

- _includes/article/hero.liquid
- jekyll-theme-platoniq-journal.gemspec
- Use mobile image in article hero
- Bump version
> Use mobile image in article hero

- _includes/netlifycms/collections/Article.liquid
- _includes/netlifycms/collections/Author.liquid
- _includes/netlifycms/collections/StickerPack.liquid
- _includes/netlifycms/scripts/editor_component_author_tag.liquid
- _includes/netlifycms/scripts/editor_component_quote_tag.liquid
- jekyll-theme-platoniq-journal.gemspec
- Replace autorx with autoría
- Bump version
> Improve CMS

- _includes/article/assigns.liquid
- _includes/article/hero.liquid
- _includes/default/related_article.liquid
- _includes/journal/section_main.liquid
- _includes/netlifycms/collections/Author.liquid
- _layouts/archive/category.html
- _layouts/netlifycms/config.yml
- _layouts/sticker_pack.html
- jekyll-theme-platoniq-journal.gemspec
- Use author as string
- Bump version
> Use author as string

- _data/i18n/en/pagination.yml
- _data/i18n/es/pagination.yml
- _includes/article/pagination.liquid
- _sass/partials/_footer.scss
- jekyll-theme-platoniq-journal.gemspec
- Prepend "inteviewing ..." in pagination interview titles
- Fix footer width on mobile
- Bump version
> Fix design details

- _data/i18n/en/pagination.yml
- _data/i18n/es/pagination.yml
- _includes/article/pagination.liquid
- _sass/partials/page/_articles.scss
- jekyll-theme-platoniq-journal.gemspec
- Prepend 'stories' to pagination
- Improve story article page style
> Design improvements

- _includes/article/author.liquid
- _includes/netlifycms/scripts/editor_component_author_tag.liquid
- _layouts/article.html
- _sass/plugins/tags/_author.scss
- assets/js/main.js
- jekyll-theme-platoniq-journal.gemspec
- Add author plugin as well as article section
- Bump version
> Add author plugin as well as section in article

- PLUGINS.md
- _includes/netlifycms/collections/Article.liquid
- _includes/netlifycms/scripts/editor_component_gallery.liquid
- jekyll-theme-platoniq-journal.gemspec
- Remove field for article social image alt
- Remove 'bw' field for gallery
- Bump version
- Update plugins doc
> Remove social image alt text for article in CMS

- _layouts/sticker_pack.html
- jekyll-theme-platoniq-journal.gemspec
- Add author card to sticker pack page
- Bump version
> Add author card to sticker pack page

- _includes/article/author.liquid
- _includes/article/related_articles.liquid
- _includes/default/cookies.js
- _includes/default/cookies.liquid
- _sass/base/_burger.scss
- _sass/base/_variables.scss
- _sass/partials/_cookies.scss
- _sass/partials/_footer.scss
- _sass/partials/_related_articles.scss
- _sass/partials/_stickers.scss
- _sass/partials/home/_home_hero.scss
- _sass/partials/home/_home_reports.scss
- _sass/partials/page/_elements.scss
- _sass/plugins/blocks/_cta.scss
- assets/js/main.js
- jekyll-theme-platoniq-journal.gemspec
- Add close button to author and cookies banner
- Adjust sticker size for mobile
- Don't render unpublished related articles
- Remove related articles author red line
- fix footer credits width
- Fix homepage cover for lower width desktop viewports
- Bump version
- Adjust for mini mobiles (320px)
> Fix various design and accessibility issues

- _data/i18n/en/categories.yml
- _data/i18n/es/categories.yml
- _includes/default/head.liquid
- _includes/default/header_sitemap_selector.liquid
- _includes/netlifycms/collections/Article.liquid
- add new service archive
- add new service and content to header
> Add service archive
